/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IFundPoolInterface extends ethers.utils.Interface {
  functions: {
    "balanceOf(address,bytes32)": FunctionFragment;
    "celerExec(uint256,bytes)": FunctionFragment;
    "initWalletAndWithdraw(address,bytes32,bytes,bytes,uint256,uint64,bytes,address,uint256)": FunctionFragment;
    "recharge(address,bytes32,uint256)": FunctionFragment;
    "spend(address,bytes32,bytes,uint256,uint64,bytes)": FunctionFragment;
    "walletOf(address,bytes32)": FunctionFragment;
    "withdraw(address,bytes32,bytes,uint256,uint64,bytes,address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "celerExec",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initWalletAndWithdraw",
    values: [
      string,
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "recharge",
    values: [string, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "spend",
    values: [
      string,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "walletOf",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [
      string,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      string,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "celerExec", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initWalletAndWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "recharge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "spend", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "walletOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "Recharged(address,bytes32,uint256)": EventFragment;
    "Spent(address,bytes32,uint256)": EventFragment;
    "Withdrawn(address,bytes32,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Recharged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Spent"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdrawn"): EventFragment;
}

export type RechargedEvent = TypedEvent<
  [string, string, BigNumber] & {
    provider: string;
    account: string;
    amount: BigNumber;
  }
>;

export type SpentEvent = TypedEvent<
  [string, string, BigNumber] & {
    provider: string;
    account: string;
    amount: BigNumber;
  }
>;

export type WithdrawnEvent = TypedEvent<
  [string, string, string, BigNumber] & {
    provider: string;
    account: string;
    to: string;
    amount: BigNumber;
  }
>;

export class IFundPool extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IFundPoolInterface;

  functions: {
    balanceOf(
      provider: string,
      account: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    celerExec(
      amount: BigNumberish,
      message: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initWalletAndWithdraw(
      provider: string,
      account: BytesLike,
      walletSig: BytesLike,
      bills: BytesLike,
      timeout: BigNumberish,
      nonce: BigNumberish,
      billSig: BytesLike,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    recharge(
      provider: string,
      account: BytesLike,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    spend(
      provider: string,
      account: BytesLike,
      bills: BytesLike,
      timeout: BigNumberish,
      nonce: BigNumberish,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    walletOf(
      provider: string,
      account: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    withdraw(
      provider: string,
      account: BytesLike,
      bills: BytesLike,
      timeout: BigNumberish,
      nonce: BigNumberish,
      signature: BytesLike,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  balanceOf(
    provider: string,
    account: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  celerExec(
    amount: BigNumberish,
    message: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initWalletAndWithdraw(
    provider: string,
    account: BytesLike,
    walletSig: BytesLike,
    bills: BytesLike,
    timeout: BigNumberish,
    nonce: BigNumberish,
    billSig: BytesLike,
    to: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  recharge(
    provider: string,
    account: BytesLike,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  spend(
    provider: string,
    account: BytesLike,
    bills: BytesLike,
    timeout: BigNumberish,
    nonce: BigNumberish,
    signature: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  walletOf(
    provider: string,
    account: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  withdraw(
    provider: string,
    account: BytesLike,
    bills: BytesLike,
    timeout: BigNumberish,
    nonce: BigNumberish,
    signature: BytesLike,
    to: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    balanceOf(
      provider: string,
      account: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    celerExec(
      amount: BigNumberish,
      message: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    initWalletAndWithdraw(
      provider: string,
      account: BytesLike,
      walletSig: BytesLike,
      bills: BytesLike,
      timeout: BigNumberish,
      nonce: BigNumberish,
      billSig: BytesLike,
      to: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    recharge(
      provider: string,
      account: BytesLike,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    spend(
      provider: string,
      account: BytesLike,
      bills: BytesLike,
      timeout: BigNumberish,
      nonce: BigNumberish,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    walletOf(
      provider: string,
      account: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    withdraw(
      provider: string,
      account: BytesLike,
      bills: BytesLike,
      timeout: BigNumberish,
      nonce: BigNumberish,
      signature: BytesLike,
      to: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "Recharged(address,bytes32,uint256)"(
      provider?: null,
      account?: null,
      amount?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { provider: string; account: string; amount: BigNumber }
    >;

    Recharged(
      provider?: null,
      account?: null,
      amount?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { provider: string; account: string; amount: BigNumber }
    >;

    "Spent(address,bytes32,uint256)"(
      provider?: null,
      account?: null,
      amount?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { provider: string; account: string; amount: BigNumber }
    >;

    Spent(
      provider?: null,
      account?: null,
      amount?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { provider: string; account: string; amount: BigNumber }
    >;

    "Withdrawn(address,bytes32,address,uint256)"(
      provider?: null,
      account?: null,
      to?: null,
      amount?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber],
      { provider: string; account: string; to: string; amount: BigNumber }
    >;

    Withdrawn(
      provider?: null,
      account?: null,
      to?: null,
      amount?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber],
      { provider: string; account: string; to: string; amount: BigNumber }
    >;
  };

  estimateGas: {
    balanceOf(
      provider: string,
      account: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    celerExec(
      amount: BigNumberish,
      message: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initWalletAndWithdraw(
      provider: string,
      account: BytesLike,
      walletSig: BytesLike,
      bills: BytesLike,
      timeout: BigNumberish,
      nonce: BigNumberish,
      billSig: BytesLike,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    recharge(
      provider: string,
      account: BytesLike,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    spend(
      provider: string,
      account: BytesLike,
      bills: BytesLike,
      timeout: BigNumberish,
      nonce: BigNumberish,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    walletOf(
      provider: string,
      account: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdraw(
      provider: string,
      account: BytesLike,
      bills: BytesLike,
      timeout: BigNumberish,
      nonce: BigNumberish,
      signature: BytesLike,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    balanceOf(
      provider: string,
      account: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    celerExec(
      amount: BigNumberish,
      message: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initWalletAndWithdraw(
      provider: string,
      account: BytesLike,
      walletSig: BytesLike,
      bills: BytesLike,
      timeout: BigNumberish,
      nonce: BigNumberish,
      billSig: BytesLike,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    recharge(
      provider: string,
      account: BytesLike,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    spend(
      provider: string,
      account: BytesLike,
      bills: BytesLike,
      timeout: BigNumberish,
      nonce: BigNumberish,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    walletOf(
      provider: string,
      account: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdraw(
      provider: string,
      account: BytesLike,
      bills: BytesLike,
      timeout: BigNumberish,
      nonce: BigNumberish,
      signature: BytesLike,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
