/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface RouterInterface extends ethers.utils.Interface {
  functions: {
    "ARStorageController()": FunctionFragment;
    "BandwidthController()": FunctionFragment;
    "Billing()": FunctionFragment;
    "BuildingTimeController()": FunctionFragment;
    "DstChainPayment()": FunctionFragment;
    "FundPool()": FunctionFragment;
    "Governance()": FunctionFragment;
    "IPFSStorageController()": FunctionFragment;
    "MessageReceiver()": FunctionFragment;
    "ProviderController()": FunctionFragment;
    "ProviderRegistry()": FunctionFragment;
    "ResourcePriceAdaptor()": FunctionFragment;
    "Token()": FunctionFragment;
    "initialize(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setARStorageController(address)": FunctionFragment;
    "setBandwidthController(address)": FunctionFragment;
    "setBilling(address)": FunctionFragment;
    "setBuildingTimeController(address)": FunctionFragment;
    "setDstChainPayment(address)": FunctionFragment;
    "setFundPool(address)": FunctionFragment;
    "setGovernance(address)": FunctionFragment;
    "setIPFSStorageController(address)": FunctionFragment;
    "setMessageReceiver(address)": FunctionFragment;
    "setProviderController(address)": FunctionFragment;
    "setProviderRegistry(address)": FunctionFragment;
    "setResourcePriceAdaptor(address)": FunctionFragment;
    "setToken(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "ARStorageController",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BandwidthController",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "Billing", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "BuildingTimeController",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DstChainPayment",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "FundPool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "Governance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "IPFSStorageController",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MessageReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ProviderController",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ProviderRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ResourcePriceAdaptor",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "Token", values?: undefined): string;
  encodeFunctionData(functionFragment: "initialize", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setARStorageController",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setBandwidthController",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "setBilling", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setBuildingTimeController",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setDstChainPayment",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "setFundPool", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setGovernance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setIPFSStorageController",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setMessageReceiver",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setProviderController",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setProviderRegistry",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setResourcePriceAdaptor",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "setToken", values: [string]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "ARStorageController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BandwidthController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "Billing", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "BuildingTimeController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DstChainPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "FundPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "Governance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "IPFSStorageController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MessageReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ProviderController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ProviderRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ResourcePriceAdaptor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "Token", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setARStorageController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBandwidthController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBilling", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setBuildingTimeController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDstChainPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFundPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIPFSStorageController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMessageReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProviderController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProviderRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setResourcePriceAdaptor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "ARStorageControllerUpdated(address)": EventFragment;
    "BandwidthControllerUpdated(address)": EventFragment;
    "BillingUpdated(address)": EventFragment;
    "BuildingTimeControllerUpdated(address)": EventFragment;
    "DstChainPaymentUpdated(address)": EventFragment;
    "FundPoolUpdated(address)": EventFragment;
    "GovernanceUpdated(address)": EventFragment;
    "IPFSStorageControllerUpdated(address)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "MessageReceiverUpdated(address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "ProviderControllerUpdated(address)": EventFragment;
    "ProviderRegistryUpdated(address)": EventFragment;
    "ResourcePriceAdaptorUpdated(address)": EventFragment;
    "TokenUpdated(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ARStorageControllerUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BandwidthControllerUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BillingUpdated"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "BuildingTimeControllerUpdated"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DstChainPaymentUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FundPoolUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GovernanceUpdated"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "IPFSStorageControllerUpdated"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MessageReceiverUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProviderControllerUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProviderRegistryUpdated"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ResourcePriceAdaptorUpdated"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenUpdated"): EventFragment;
}

export type ARStorageControllerUpdatedEvent = TypedEvent<
  [string] & { arStorageController: string }
>;

export type BandwidthControllerUpdatedEvent = TypedEvent<
  [string] & { bandwidthController: string }
>;

export type BillingUpdatedEvent = TypedEvent<[string] & { billing: string }>;

export type BuildingTimeControllerUpdatedEvent = TypedEvent<
  [string] & { buildingTimeController: string }
>;

export type DstChainPaymentUpdatedEvent = TypedEvent<
  [string] & { dstChainPayment: string }
>;

export type FundPoolUpdatedEvent = TypedEvent<[string] & { fundPool: string }>;

export type GovernanceUpdatedEvent = TypedEvent<
  [string] & { governance: string }
>;

export type IPFSStorageControllerUpdatedEvent = TypedEvent<
  [string] & { ipfsStorageController: string }
>;

export type InitializedEvent = TypedEvent<[number] & { version: number }>;

export type MessageReceiverUpdatedEvent = TypedEvent<
  [string] & { messageReceiver: string }
>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type ProviderControllerUpdatedEvent = TypedEvent<
  [string] & { providerController: string }
>;

export type ProviderRegistryUpdatedEvent = TypedEvent<
  [string] & { _providerRegistry: string }
>;

export type ResourcePriceAdaptorUpdatedEvent = TypedEvent<
  [string] & { resourcePriceAdaptor: string }
>;

export type TokenUpdatedEvent = TypedEvent<[string] & { token: string }>;

export class Router extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: RouterInterface;

  functions: {
    ARStorageController(overrides?: CallOverrides): Promise<[string]>;

    BandwidthController(overrides?: CallOverrides): Promise<[string]>;

    Billing(overrides?: CallOverrides): Promise<[string]>;

    BuildingTimeController(overrides?: CallOverrides): Promise<[string]>;

    DstChainPayment(overrides?: CallOverrides): Promise<[string]>;

    FundPool(overrides?: CallOverrides): Promise<[string]>;

    Governance(overrides?: CallOverrides): Promise<[string]>;

    IPFSStorageController(overrides?: CallOverrides): Promise<[string]>;

    MessageReceiver(overrides?: CallOverrides): Promise<[string]>;

    ProviderController(overrides?: CallOverrides): Promise<[string]>;

    ProviderRegistry(overrides?: CallOverrides): Promise<[string]>;

    ResourcePriceAdaptor(overrides?: CallOverrides): Promise<[string]>;

    Token(overrides?: CallOverrides): Promise<[string]>;

    initialize(
      owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setARStorageController(
      _arStorageController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setBandwidthController(
      _bandwidthController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setBilling(
      _billing: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setBuildingTimeController(
      _buildingTimeController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDstChainPayment(
      _dstChainPayment: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setFundPool(
      _pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setGovernance(
      _governance: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setIPFSStorageController(
      _ipfsStorageController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMessageReceiver(
      _messageReceiver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setProviderController(
      _providerController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setProviderRegistry(
      _providerRegistry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setResourcePriceAdaptor(
      _resourcePriceAdaptor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setToken(
      _token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  ARStorageController(overrides?: CallOverrides): Promise<string>;

  BandwidthController(overrides?: CallOverrides): Promise<string>;

  Billing(overrides?: CallOverrides): Promise<string>;

  BuildingTimeController(overrides?: CallOverrides): Promise<string>;

  DstChainPayment(overrides?: CallOverrides): Promise<string>;

  FundPool(overrides?: CallOverrides): Promise<string>;

  Governance(overrides?: CallOverrides): Promise<string>;

  IPFSStorageController(overrides?: CallOverrides): Promise<string>;

  MessageReceiver(overrides?: CallOverrides): Promise<string>;

  ProviderController(overrides?: CallOverrides): Promise<string>;

  ProviderRegistry(overrides?: CallOverrides): Promise<string>;

  ResourcePriceAdaptor(overrides?: CallOverrides): Promise<string>;

  Token(overrides?: CallOverrides): Promise<string>;

  initialize(
    owner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setARStorageController(
    _arStorageController: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setBandwidthController(
    _bandwidthController: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setBilling(
    _billing: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setBuildingTimeController(
    _buildingTimeController: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDstChainPayment(
    _dstChainPayment: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setFundPool(
    _pool: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setGovernance(
    _governance: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setIPFSStorageController(
    _ipfsStorageController: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMessageReceiver(
    _messageReceiver: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setProviderController(
    _providerController: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setProviderRegistry(
    _providerRegistry: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setResourcePriceAdaptor(
    _resourcePriceAdaptor: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setToken(
    _token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    ARStorageController(overrides?: CallOverrides): Promise<string>;

    BandwidthController(overrides?: CallOverrides): Promise<string>;

    Billing(overrides?: CallOverrides): Promise<string>;

    BuildingTimeController(overrides?: CallOverrides): Promise<string>;

    DstChainPayment(overrides?: CallOverrides): Promise<string>;

    FundPool(overrides?: CallOverrides): Promise<string>;

    Governance(overrides?: CallOverrides): Promise<string>;

    IPFSStorageController(overrides?: CallOverrides): Promise<string>;

    MessageReceiver(overrides?: CallOverrides): Promise<string>;

    ProviderController(overrides?: CallOverrides): Promise<string>;

    ProviderRegistry(overrides?: CallOverrides): Promise<string>;

    ResourcePriceAdaptor(overrides?: CallOverrides): Promise<string>;

    Token(overrides?: CallOverrides): Promise<string>;

    initialize(owner: string, overrides?: CallOverrides): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setARStorageController(
      _arStorageController: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setBandwidthController(
      _bandwidthController: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setBilling(_billing: string, overrides?: CallOverrides): Promise<void>;

    setBuildingTimeController(
      _buildingTimeController: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setDstChainPayment(
      _dstChainPayment: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setFundPool(_pool: string, overrides?: CallOverrides): Promise<void>;

    setGovernance(
      _governance: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setIPFSStorageController(
      _ipfsStorageController: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setMessageReceiver(
      _messageReceiver: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setProviderController(
      _providerController: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setProviderRegistry(
      _providerRegistry: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setResourcePriceAdaptor(
      _resourcePriceAdaptor: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setToken(_token: string, overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ARStorageControllerUpdated(address)"(
      arStorageController?: null
    ): TypedEventFilter<[string], { arStorageController: string }>;

    ARStorageControllerUpdated(
      arStorageController?: null
    ): TypedEventFilter<[string], { arStorageController: string }>;

    "BandwidthControllerUpdated(address)"(
      bandwidthController?: null
    ): TypedEventFilter<[string], { bandwidthController: string }>;

    BandwidthControllerUpdated(
      bandwidthController?: null
    ): TypedEventFilter<[string], { bandwidthController: string }>;

    "BillingUpdated(address)"(
      billing?: null
    ): TypedEventFilter<[string], { billing: string }>;

    BillingUpdated(
      billing?: null
    ): TypedEventFilter<[string], { billing: string }>;

    "BuildingTimeControllerUpdated(address)"(
      buildingTimeController?: null
    ): TypedEventFilter<[string], { buildingTimeController: string }>;

    BuildingTimeControllerUpdated(
      buildingTimeController?: null
    ): TypedEventFilter<[string], { buildingTimeController: string }>;

    "DstChainPaymentUpdated(address)"(
      dstChainPayment?: null
    ): TypedEventFilter<[string], { dstChainPayment: string }>;

    DstChainPaymentUpdated(
      dstChainPayment?: null
    ): TypedEventFilter<[string], { dstChainPayment: string }>;

    "FundPoolUpdated(address)"(
      fundPool?: null
    ): TypedEventFilter<[string], { fundPool: string }>;

    FundPoolUpdated(
      fundPool?: null
    ): TypedEventFilter<[string], { fundPool: string }>;

    "GovernanceUpdated(address)"(
      governance?: null
    ): TypedEventFilter<[string], { governance: string }>;

    GovernanceUpdated(
      governance?: null
    ): TypedEventFilter<[string], { governance: string }>;

    "IPFSStorageControllerUpdated(address)"(
      ipfsStorageController?: null
    ): TypedEventFilter<[string], { ipfsStorageController: string }>;

    IPFSStorageControllerUpdated(
      ipfsStorageController?: null
    ): TypedEventFilter<[string], { ipfsStorageController: string }>;

    "Initialized(uint8)"(
      version?: null
    ): TypedEventFilter<[number], { version: number }>;

    Initialized(
      version?: null
    ): TypedEventFilter<[number], { version: number }>;

    "MessageReceiverUpdated(address)"(
      messageReceiver?: null
    ): TypedEventFilter<[string], { messageReceiver: string }>;

    MessageReceiverUpdated(
      messageReceiver?: null
    ): TypedEventFilter<[string], { messageReceiver: string }>;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "ProviderControllerUpdated(address)"(
      providerController?: null
    ): TypedEventFilter<[string], { providerController: string }>;

    ProviderControllerUpdated(
      providerController?: null
    ): TypedEventFilter<[string], { providerController: string }>;

    "ProviderRegistryUpdated(address)"(
      _providerRegistry?: null
    ): TypedEventFilter<[string], { _providerRegistry: string }>;

    ProviderRegistryUpdated(
      _providerRegistry?: null
    ): TypedEventFilter<[string], { _providerRegistry: string }>;

    "ResourcePriceAdaptorUpdated(address)"(
      resourcePriceAdaptor?: null
    ): TypedEventFilter<[string], { resourcePriceAdaptor: string }>;

    ResourcePriceAdaptorUpdated(
      resourcePriceAdaptor?: null
    ): TypedEventFilter<[string], { resourcePriceAdaptor: string }>;

    "TokenUpdated(address)"(
      token?: null
    ): TypedEventFilter<[string], { token: string }>;

    TokenUpdated(token?: null): TypedEventFilter<[string], { token: string }>;
  };

  estimateGas: {
    ARStorageController(overrides?: CallOverrides): Promise<BigNumber>;

    BandwidthController(overrides?: CallOverrides): Promise<BigNumber>;

    Billing(overrides?: CallOverrides): Promise<BigNumber>;

    BuildingTimeController(overrides?: CallOverrides): Promise<BigNumber>;

    DstChainPayment(overrides?: CallOverrides): Promise<BigNumber>;

    FundPool(overrides?: CallOverrides): Promise<BigNumber>;

    Governance(overrides?: CallOverrides): Promise<BigNumber>;

    IPFSStorageController(overrides?: CallOverrides): Promise<BigNumber>;

    MessageReceiver(overrides?: CallOverrides): Promise<BigNumber>;

    ProviderController(overrides?: CallOverrides): Promise<BigNumber>;

    ProviderRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    ResourcePriceAdaptor(overrides?: CallOverrides): Promise<BigNumber>;

    Token(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setARStorageController(
      _arStorageController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setBandwidthController(
      _bandwidthController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setBilling(
      _billing: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setBuildingTimeController(
      _buildingTimeController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDstChainPayment(
      _dstChainPayment: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setFundPool(
      _pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setGovernance(
      _governance: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setIPFSStorageController(
      _ipfsStorageController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMessageReceiver(
      _messageReceiver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setProviderController(
      _providerController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setProviderRegistry(
      _providerRegistry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setResourcePriceAdaptor(
      _resourcePriceAdaptor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setToken(
      _token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ARStorageController(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    BandwidthController(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    Billing(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    BuildingTimeController(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    DstChainPayment(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    FundPool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    Governance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    IPFSStorageController(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MessageReceiver(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ProviderController(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ProviderRegistry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ResourcePriceAdaptor(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    Token(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setARStorageController(
      _arStorageController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setBandwidthController(
      _bandwidthController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setBilling(
      _billing: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setBuildingTimeController(
      _buildingTimeController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDstChainPayment(
      _dstChainPayment: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setFundPool(
      _pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setGovernance(
      _governance: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setIPFSStorageController(
      _ipfsStorageController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMessageReceiver(
      _messageReceiver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setProviderController(
      _providerController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setProviderRegistry(
      _providerRegistry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setResourcePriceAdaptor(
      _resourcePriceAdaptor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setToken(
      _token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
