/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IResource, IResourceInterface } from "../IResource";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "enum ResourceData.ResourceType",
        name: "resourceType",
        type: "uint8",
      },
    ],
    name: "ResourceTypeUpdated",
    type: "event",
  },
  {
    inputs: [],
    name: "resourceType",
    outputs: [
      {
        internalType: "enum ResourceData.ResourceType",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IResource__factory {
  static readonly abi = _abi;
  static createInterface(): IResourceInterface {
    return new utils.Interface(_abi) as IResourceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IResource {
    return new Contract(address, _abi, signerOrProvider) as IResource;
  }
}
